// SPDX-License-Identifier: MIT
//! Report rendering: `risk-grid.csv` and `RISK.md`.
//!
//! Floats are formatted with Rust's own (platform-independent) formatter at fixed precision, so the committed
//! files can be compared byte for byte.

use std::fmt::Write as _;

use crate::config::SimConfig;
use crate::sim::Cell;
use crate::sweep::{CellStats, SeedCheck, recommend};

fn pct(x: f64) -> String {
    format!("{:.3}%", x * 100.0)
}

fn bps_pct(bps: u64) -> String {
    format!("{}.{:02}%", bps / 100, bps % 100)
}

/// Renders the grid as CSV.
pub fn render_csv(stats: &[CellStats]) -> anyhow::Result<String> {
    // LF terminators (the csv crate defaults to CRLF) keep the golden file identical on every OS.
    let mut writer = csv::WriterBuilder::new().terminator(csv::Terminator::Any(b'\n')).from_writer(Vec::new());
    writer.write_record([
        "lltv_bps",
        "bonus_cap_bps",
        "valid",
        "paths",
        "initial_ltv",
        "mean_bad_debt",
        "p95_bad_debt",
        "p99_bad_debt",
        "p99_ci_low",
        "p99_ci_high",
        "max_bad_debt",
        "prob_bad_debt",
        "mean_liquidations",
        "mean_closeouts",
        "mean_liquidator_profit",
        "mean_unprofitable_skips",
        "mean_min_price",
    ])?;
    for s in stats {
        writer.write_record([
            s.cell.lltv_bps.to_string(),
            s.cell.bonus_cap_bps.to_string(),
            s.valid.to_string(),
            s.paths.to_string(),
            format!("{:.6}", s.initial_ltv),
            format!("{:.8}", s.mean_bad_debt),
            format!("{:.8}", s.p95_bad_debt),
            format!("{:.8}", s.p99_bad_debt),
            format!("{:.8}", s.p99_ci_low),
            format!("{:.8}", s.p99_ci_high),
            format!("{:.8}", s.max_bad_debt),
            format!("{:.4}", s.prob_bad_debt),
            format!("{:.3}", s.mean_liquidations),
            format!("{:.3}", s.mean_closeouts),
            format!("{:.2}", s.mean_liquidator_profit),
            format!("{:.3}", s.mean_unprofitable_skips),
            format!("{:.6}", s.mean_min_price),
        ])?;
    }
    let bytes = writer.into_inner().map_err(|e| anyhow::anyhow!("csv flush: {e}"))?;
    Ok(String::from_utf8(bytes)?)
}

fn cell_label(cell: Cell) -> String {
    format!("LLTV {} / cap {}", bps_pct(cell.lltv_bps), bps_pct(cell.bonus_cap_bps))
}

fn interval(s: &CellStats) -> String {
    format!("[{}, {}]", pct(s.p99_ci_low), pct(s.p99_ci_high))
}

fn find(stats: &[CellStats], cell: Cell) -> Option<&CellStats> {
    stats.iter().find(|s| s.cell == cell)
}

/// Renders the markdown risk report. `stability` holds the recommendations of the sweep re-run on other seeds.
pub fn render_markdown(config: &SimConfig, stats: &[CellStats], stability: &[SeedCheck]) -> String {
    let (overall, per_lltv) = recommend(config, stats);
    let mut md = String::new();
    let _ = writeln!(md, "# Risk report: LLTV x liquidation bonus cap\n");
    let _ = writeln!(
        md,
        "Generated by `cargo run --release -p cascade-sim` (seed `{:#x}`, plus {} stability seeds). Do not edit by \
         hand: CI regenerates this file and compares it byte for byte.\n",
        config.seed,
        config.stability_seeds.len()
    );
    let _ = writeln!(md, "## Recommendation\n");
    match overall.and_then(|cell| find(stats, cell).map(|s| (cell, s))) {
        Some((cell, s)) => {
            let with_bad_debt = libm::round(s.prob_bad_debt * s.paths as f64) as u64;
            let _ = writeln!(
                md,
                "**{}** (slope {}x) is the most capital-efficient configuration whose p99 bad debt stays within the \
                 {} budget: p99 {} (bootstrap 95 % interval {} over the {} paths), mean {}, bad debt on {} of \
                 paths ({} of {}).\n",
                cell_label(cell),
                config.bonus_slope_bps as f64 / 10_000.0,
                pct(config.risk_budget_p99),
                pct(s.p99_bad_debt),
                interval(s),
                s.paths,
                pct(s.mean_bad_debt),
                pct(s.prob_bad_debt),
                with_bad_debt,
                s.paths,
            );
            if s.p99_ci_high > config.risk_budget_p99 {
                let _ = writeln!(
                    md,
                    "The upper end of that interval exceeds the budget: with {} paths the p99 rests on a handful of \
                     paths, so treat the recommendation as marginal at this LLTV.\n",
                    s.paths
                );
            }
        }
        None => {
            let _ = writeln!(
                md,
                "No configuration keeps p99 bad debt within the {} budget.\n",
                pct(config.risk_budget_p99)
            );
        }
    }

    if !stability.is_empty() {
        let same = stability.iter().filter(|c| c.recommended == overall).count() + 1;
        let _ = writeln!(
            md,
            "**Stability.** Re-running the whole sweep on {} more seeds recommends the same cell on {} of {} seeds:\n",
            stability.len(),
            same,
            stability.len() + 1
        );
        let main_label = overall.map_or_else(|| "none".to_string(), cell_label);
        let _ = writeln!(md, "| Seed | Recommended | p99 bad debt of {main_label} |");
        let _ = writeln!(md, "|---|---|---|");
        let main_p99 = overall.and_then(|cell| find(stats, cell)).map(|s| s.p99_bad_debt);
        let rows = std::iter::once((config.seed, overall, main_p99, " (main)"))
            .chain(stability.iter().map(|c| (c.seed, c.recommended, c.p99_of_main_choice, "")));
        for (seed, recommended, p99, tag) in rows {
            let _ = writeln!(
                md,
                "| `{seed:#x}`{tag} | {} | {} |",
                recommended.map_or_else(|| "none".to_string(), cell_label),
                p99.map_or_else(|| "-".to_string(), pct)
            );
        }
        md.push('\n');
    }

    if let Some(cell) = overall {
        let row: Vec<&CellStats> = stats.iter().filter(|s| s.valid && s.cell.lltv_bps == cell.lltv_bps).collect();
        let listed: Vec<String> =
            row.iter().map(|s| format!("{} {}", bps_pct(s.cell.bonus_cap_bps), pct(s.p99_bad_debt))).collect();
        let best = per_lltv.iter().find(|c| c.lltv_bps == cell.lltv_bps).and_then(|c| find(stats, *c));
        let position = match (best, row.first(), row.last()) {
            (Some(b), Some(lo), _) if b.cell == lo.cell => "the lowest cap in the grid".to_string(),
            (Some(b), _, Some(hi)) if b.cell == hi.cell => "the highest cap in the grid".to_string(),
            (Some(b), Some(lo), Some(hi)) => format!(
                "{}, inside the grid: p99 rises again at both ends ({} at {}, {} at {}); ties on p99 go to the lower \
                 mean bad debt, then to the lower cap",
                bps_pct(b.cell.bonus_cap_bps),
                pct(lo.p99_bad_debt),
                bps_pct(lo.cell.bonus_cap_bps),
                pct(hi.p99_bad_debt),
                bps_pct(hi.cell.bonus_cap_bps)
            ),
            _ => "undetermined".to_string(),
        };
        let _ = writeln!(
            md,
            "At LLTV {}, p99 bad debt by bonus cap is {}. The best cap there is {}. Two effects pull in opposite \
             directions. A low cap pays too little to cover pool slippage and gas near the threshold (see the \
             unprofitable-skip counts below), so positions can drift under water before anyone closes them. A high \
             cap reaches the \"collateral cannot cover debt plus bonus\" region at a smaller price drop and, once a \
             position is under water, pays the liquidator more of the collateral that would otherwise repay \
             suppliers. Above water the engine caps a closeout's bonus at the borrower's equity, so no cap turns a \
             position with positive equity into a supplier loss.\n",
            bps_pct(cell.lltv_bps),
            listed.join(", "),
            position,
        );
    }
    let _ = writeln!(md, "Best bonus cap for each LLTV (lowest p99 bad debt, ties to the lower cap):\n");
    let _ = writeln!(
        md,
        "| LLTV | Best cap | Initial LTV | Mean bad debt | p99 bad debt | p99 95 % interval | Liquidations / path |"
    );
    let _ = writeln!(md, "|---|---|---|---|---|---|---|");
    for cell in &per_lltv {
        if let Some(s) = find(stats, *cell) {
            let _ = writeln!(
                md,
                "| {} | {} | {} | {} | {} | {} | {:.1} |",
                bps_pct(cell.lltv_bps),
                bps_pct(cell.bonus_cap_bps),
                pct(s.initial_ltv),
                pct(s.mean_bad_debt),
                pct(s.p99_bad_debt),
                interval(s),
                s.mean_liquidations
            );
        }
    }

    let _ = writeln!(md, "\n## p99 bad debt (share of initial borrows)\n");
    let mut header = String::from("| LLTV \\ cap |");
    let mut rule = String::from("|---|");
    for &cap in &config.bonus_caps_bps {
        let _ = write!(header, " {} |", bps_pct(cap));
        rule.push_str("---|");
    }
    let _ = writeln!(md, "{header}\n{rule}");
    for &lltv in &config.lltvs_bps {
        let mut row = format!("| {} |", bps_pct(lltv));
        for &cap in &config.bonus_caps_bps {
            match find(stats, Cell { lltv_bps: lltv, bonus_cap_bps: cap }) {
                Some(s) if s.valid => {
                    let _ = write!(row, " {} |", pct(s.p99_bad_debt));
                }
                _ => row.push_str(" rejected by `enableLltv` |"),
            }
        }
        let _ = writeln!(md, "{row}");
    }

    let _ = writeln!(md, "\n## Mean bad debt and liquidation activity\n");
    let _ = writeln!(
        md,
        "| Cell | Mean bad debt | p95 | p99 95 % interval | Paths with bad debt | Liquidations | Closeouts | Unprofitable skips | Liquidator profit / path |"
    );
    let _ = writeln!(md, "|---|---|---|---|---|---|---|---|---|");
    for s in stats.iter().filter(|s| s.valid) {
        let _ = writeln!(
            md,
            "| {} | {} | {} | {} | {} | {:.1} | {:.2} | {:.1} | {:.0} |",
            cell_label(s.cell),
            pct(s.mean_bad_debt),
            pct(s.p95_bad_debt),
            interval(s),
            pct(s.prob_bad_debt),
            s.mean_liquidations,
            s.mean_closeouts,
            s.mean_unprofitable_skips,
            s.mean_liquidator_profit
        );
    }

    let _ = writeln!(md, "\n## Model\n");
    let _ = writeln!(md, "| Parameter | Value |");
    let _ = writeln!(md, "|---|---|");
    let seeds = config.stability_seeds.iter().map(|s| format!("{s:#x}")).collect::<Vec<_>>().join(", ");
    let rows: [(&str, String); 18] = [
        ("Paths per cell", config.paths.to_string()),
        ("Horizon", format!("{} blocks of {} s", config.steps, config.block_seconds)),
        ("Borrowers", config.borrowers.to_string()),
        ("Collateral posted", format!("{:.0} (loan units)", config.total_collateral_value)),
        ("Position sizes", format!("log-normal, sigma {}", config.position_size_sigma)),
        ("Capacity used per borrower", format!("uniform [{}, {})", config.min_capacity_used, config.max_capacity_used)),
        ("Volatility", format!("{} annualized", config.annual_volatility)),
        (
            "Jumps",
            format!(
                "{} per day, log size N({}, {}^2), not drift-compensated",
                config.jumps_per_day, config.jump_log_mean, config.jump_log_std
            ),
        ),
        ("Pool depth", format!("{:.0} loan tokens, fee {}", config.amm_loan_reserve, config.amm_fee)),
        ("Arbitrage speed", format!("{} of the gap per block", config.arbitrage_speed)),
        ("Liquidator latency", format!("{} blocks", config.liquidator_latency_blocks)),
        ("Gas per liquidation", format!("{} loan units", config.gas_cost)),
        ("Bonus slope", format!("{}x", config.bonus_slope_bps as f64 / 10_000.0)),
        ("Market utilization at start", config.initial_utilization.to_string()),
        ("Risk budget", format!("p99 bad debt <= {}", pct(config.risk_budget_p99))),
        ("p99 interval", format!("percentile bootstrap, {} resamples of the paths", config.bootstrap_resamples)),
        ("Seed", format!("{:#x}", config.seed)),
        ("Stability seeds", if seeds.is_empty() { "none".to_string() } else { seeds }),
    ];
    for (k, v) in rows {
        let _ = writeln!(md, "| {k} | {v} |");
    }
    let _ = writeln!(
        md,
        "\nEvery liquidation is priced and applied with `risk-math`, the Rust port of the contract arithmetic. \
         `test/vectors/HealthVectors.t.sol` checks it bit for bit against the engine on 100 shared vectors; those \
         cover the liquidation state transition only (not interest accrual, the IRM or the oracle path, none of which \
         the simulator models). Bad debt is what the engine writes off during closeouts plus, at the horizon, the \
         shortfall of positions nobody liquidated. p99 is the nearest-rank percentile of the per-path bad debt, so \
         with 400 paths it is the fifth-worst path.\n"
    );
    let _ = writeln!(md, "## Limitations\n");
    let _ = writeln!(
        md,
        "- Stress calibration, not a forecast: high volatility and downward jumps that are not drift-compensated.\n\
         - Borrowers are passive (no top-ups or deleveraging), which overstates liquidations.\n\
         - One pool with constant depth; real depth thins out in crashes, which would understate cascades.\n\
         - Interest is not accrued over the one-day horizon.\n\
         - Liquidators are a single competitive population with fixed latency and gas; no MEV auctions or \
         priority-fee wars.\n\
         - The oracle is the pool mid price; no oracle lag or deviation threshold.\n\
         - The grid is coarse (six caps, five LLTVs); the optimum between grid points is not resolved."
    );
    md
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn percentages_render_exactly() {
        assert_eq!(bps_pct(8_600), "86.00%");
        assert_eq!(bps_pct(625), "6.25%");
        assert_eq!(pct(0.0123456), "1.235%");
    }
}
