# SPDX-License-Identifier: MIT
"""Generate test/fixtures/gbm_paths.json: seeded geometric-Brownian-motion price paths plus noise-trader flow.

Usage (from the project root):
    uv run --project sim python sim/gen_paths.py          # (re)write the fixture
    uv run --project sim python sim/gen_paths.py --check  # fail if the committed fixture is stale

Model (per block, 12 s):
  * External (CEX) price: log P[t+1] = log P[t] - sigma^2 / 2 + sigma * Z, Z ~ N(0, 1), stored as the nearest tick
    (1 tick = 1.0001x). sigma is quoted in basis points per block.
  * Up to NOISE_SLOTS uninformed trades per block, each present with probability NOISE_PROBABILITY, with a random
    direction, a log-normal size, and a random maximum fee it is willing to pay (elastic demand).
The replay test (test/replay/GbmReplay.t.sol) runs the same flow through the hook pool and a static 30 bps pool.
Normal variates come from a SHA-256 counter RNG and mpmath, so the fixture is byte-identical on every platform.
"""

from __future__ import annotations

import argparse
import sys

import mpmath

from volfee_model import FIXTURES, Sha256Rng, dump_json, write_or_check

SEED = "v4-volatility-fee-hook/gbm-paths/v1"
BLOCKS = 400
NOISE_SLOTS = 2
NOISE_PROBABILITY_PERCENT = 60
NOISE_MEDIAN_SIZE = 5 * 10**16  # 0.05 token (~0.02% of the ~260 of each token in range, ~1 tick of impact)
NOISE_SIZE_LOG_STDEV = mpmath.mpf("0.8")
NOISE_MIN_FEE_PIPS = 500  # the most fee-sensitive noise trader accepts 5 bps
NOISE_MAX_FEE_PIPS = 6_000  # the least fee-sensitive accepts 60 bps
LOG_TICK = mpmath.log(mpmath.mpf("1.0001"))

# (name, list of (blocks, sigma in bps per block)); annualised vol ~ sigma * sqrt(2.628e6 blocks/year).
REGIMES = [
    ("calm", [(BLOCKS, "1.5")]),
    ("normal", [(BLOCKS, "4")]),
    ("stressed", [(BLOCKS, "10")]),
    ("regime-switch", [(150, "1.5"), (100, "12"), (150, "1.5")]),
]


def generate_path(rng: Sha256Rng, schedule: list[tuple[int, str]]) -> dict:
    log_price = mpmath.mpf(0)
    ext_ticks: list[int] = []
    sigmas_bps: list[str] = []
    noise_amounts: list[int] = []
    noise_max_fees: list[int] = []
    for blocks, sigma_bps in schedule:
        sigma = mpmath.mpf(sigma_bps) / 10_000
        for _ in range(blocks):
            log_price += -sigma * sigma / 2 + sigma * rng.normal()
            ext_ticks.append(int(mpmath.nint(log_price / LOG_TICK)))
            sigmas_bps.append(sigma_bps)
            for _slot in range(NOISE_SLOTS):
                if rng.randint(1, 100) <= NOISE_PROBABILITY_PERCENT:
                    size = int(NOISE_MEDIAN_SIZE * mpmath.exp(NOISE_SIZE_LOG_STDEV * rng.normal()))
                    direction = 1 if rng.randint(0, 1) else -1
                    noise_amounts.append(direction * max(size, 1))
                    noise_max_fees.append(rng.randint(NOISE_MIN_FEE_PIPS, NOISE_MAX_FEE_PIPS))
                else:
                    noise_amounts.append(0)
                    noise_max_fees.append(0)
    return {
        "extTicks": ext_ticks,
        "noiseAmounts": noise_amounts,
        "noiseMaxFeePips": noise_max_fees,
        "sigmaBpsPerBlock": sigmas_bps,
    }


def build() -> dict:
    rng = Sha256Rng(SEED)
    paths = []
    for name, schedule in REGIMES:
        path = generate_path(rng, schedule)
        path["name"] = name
        paths.append(path)
    return {
        "blocks": BLOCKS,
        "comment": (
            "Generated by sim/gen_paths.py; do not edit by hand. noiseAmounts > 0 sells token0, < 0 sells token1."
        ),
        "noiseSlots": NOISE_SLOTS,
        "paths": paths,
        "version": 1,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify the committed fixture instead of writing it")
    args = parser.parse_args()
    content = dump_json(build())
    return write_or_check(FIXTURES / "gbm_paths.json", content, args.check)


if __name__ == "__main__":
    sys.exit(main())
