#!/usr/bin/env node
// SPDX-License-Identifier: MIT
//
// Compiles the standalone Yul object src/yul/QuartetYul.yul with npm solc@0.8.37 (standard JSON,
// language "Yul") and writes its creation and runtime bytecode as constants into
// src/generated/YulBytecode.sol, so Foundry tests, the gas bench and halmos can deploy it.
//
// Usage:
//   node scripts/build-yul.mjs           regenerate src/generated/YulBytecode.sol
//   node scripts/build-yul.mjs --check   exit 1 if regenerating would change the committed file
//
// Compiler settings mirror foundry.toml (EVM osaka, optimizer on, runs 1000000) so the Yul object is
// optimized exactly like the Solidity-compiled implementations it is compared against.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import solc from "solc";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "src", "yul", "QuartetYul.yul");
const OUTPUT = join(ROOT, "src", "generated", "YulBytecode.sol");
const EXPECTED_SOLC = "0.8.37+commit.f401782d";
const EVM_VERSION = "osaka";
const OPTIMIZER_RUNS = 1_000_000;
const OBJECT = "QuartetYul";

function fail(message) {
  console.error(`build-yul: ${message}`);
  process.exit(1);
}

function compile(source) {
  const version = solc.version();
  if (!version.startsWith(EXPECTED_SOLC)) {
    fail(`expected solc ${EXPECTED_SOLC}, found ${version}; run \`npm ci\``);
  }
  const input = {
    language: "Yul",
    sources: { "QuartetYul.yul": { content: source } },
    settings: {
      evmVersion: EVM_VERSION,
      optimizer: { enabled: true, runs: OPTIMIZER_RUNS },
      outputSelection: { "*": { "*": ["evm.bytecode.object", "evm.deployedBytecode.object"] } },
    },
  };
  const output = JSON.parse(solc.compile(JSON.stringify(input)));
  const diagnostics = output.errors ?? [];
  for (const d of diagnostics) console.error(d.formattedMessage ?? d.message);
  if (diagnostics.length > 0) fail(`solc reported ${diagnostics.length} diagnostic(s); the Yul object must compile cleanly`);

  const contract = output.contracts?.["QuartetYul.yul"]?.[OBJECT];
  const creation = contract?.evm?.bytecode?.object;
  const runtime = contract?.evm?.deployedBytecode?.object;
  if (!creation || !runtime) fail("solc produced no bytecode for object QuartetYul");
  if (!/^[0-9a-f]+$/.test(creation) || !/^[0-9a-f]+$/.test(runtime)) fail("unexpected bytecode encoding");
  return { version, creation, runtime };
}

function render({ version, creation, runtime }, sourceHash) {
  const sourcePath = relative(ROOT, SOURCE).split("\\").join("/");
  return `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by scripts/build-yul.mjs from ${sourcePath}. DO NOT EDIT.
// Regenerate with \`node scripts/build-yul.mjs\`; CI runs \`node scripts/build-yul.mjs --check\`.
// Compiler: solc ${version} (npm), language Yul, EVM ${EVM_VERSION}, optimizer runs ${OPTIMIZER_RUNS}.
// Source sha256: ${sourceHash}
pragma solidity 0.8.37;

/// @title YulBytecode
/// @notice Bytecode of the standalone Yul object QuartetYul, embedded so Solidity tests can deploy it.
library YulBytecode {
    /// @notice Creation code. Append \`abi.encode(address holder, uint256 supply)\` and CREATE it.
    bytes internal constant CREATION = hex"${creation}";

    /// @notice Runtime code as emitted by solc, with the four immutables zero-filled. The deployed code
    ///         has the same length; the constructor fills in totalSupply, the domain separator, the
    ///         chain id and the deployment address.
    bytes internal constant RUNTIME = hex"${runtime}";

    /// @notice Size of the runtime code in bytes.
    uint256 internal constant RUNTIME_SIZE = ${runtime.length / 2};
}
`;
}

const source = readFileSync(SOURCE, "utf8").replace(/\r\n/g, "\n");
const sourceHash = createHash("sha256").update(source).digest("hex");
const rendered = render(compile(source), sourceHash);

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUTPUT, "utf8").replace(/\r\n/g, "\n");
  } catch {
    fail(`${relative(ROOT, OUTPUT)} is missing; run \`node scripts/build-yul.mjs\``);
  }
  if (current !== rendered) {
    fail(`${relative(ROOT, OUTPUT)} is stale: regenerating it would change the file. Run \`node scripts/build-yul.mjs\`.`);
  }
  console.log(`build-yul: ${relative(ROOT, OUTPUT)} is up to date (source sha256 ${sourceHash.slice(0, 16)}…)`);
} else {
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, rendered);
  console.log(`build-yul: wrote ${relative(ROOT, OUTPUT)}`);
}
