// SPDX-License-Identifier: MIT
// Generates src/abi.ts (typed `as const` ABIs) from the Foundry artifacts in ../out.
// Run `forge build` first. CI regenerates the file and fails if it differs from the committed one.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "..", "out");

/** [exported name, artifact file, contract name] */
const contracts: readonly (readonly [string, string, string])[] = [
  ["originSettlerAbi", "OriginSettler.sol", "OriginSettler"],
  ["destinationSettlerAbi", "DestinationSettler.sol", "DestinationSettler"],
  ["mockMailboxAbi", "MockMailbox.sol", "MockMailbox"],
  ["mailboxFillReporterAbi", "MailboxFillReporter.sol", "MailboxFillReporter"],
  ["mailboxSettlementModuleAbi", "MailboxSettlementModule.sol", "MailboxSettlementModule"],
  ["optimisticSettlementModuleAbi", "OptimisticSettlementModule.sol", "OptimisticSettlementModule"],
  ["storageProofSettlementModuleAbi", "StorageProofSettlementModule.sol", "StorageProofSettlementModule"],
  ["headerStoreAbi", "HeaderStore.sol", "HeaderStore"],
  ["resolverAdapterAbi", "ERC7683ResolverAdapter.sol", "ERC7683ResolverAdapter"],
  ["accessManagerAbi", "AccessManager.sol", "AccessManager"],
  ["mockErc20Abi", "TestTokens.sol", "MockERC20"],
  ["permit2Abi", "Permit2.sol", "Permit2"],
];

let source = "// SPDX-License-Identifier: MIT\n";
source += "// Generated by scripts/gen-abi.ts from the Foundry artifacts. Do not edit by hand.\n";
for (const [name, file, contract] of contracts) {
  const artifact = JSON.parse(readFileSync(join(outDir, file, `${contract}.json`), "utf8")) as { abi: unknown };
  source += `\n/** ABI of \`${contract}\` (${file}). */\nexport const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}
writeFileSync(join(here, "..", "src", "abi.ts"), source);
console.log(`wrote ${contracts.length.toString()} ABIs to src/abi.ts`);
