// SPDX-License-Identifier: MIT
// @generated by scripts/gen-vectors.ts from test-vectors/amm-math.json. Do not edit.

#[test_only]
/// Differential tests: every expected value below was computed by the BigInt
/// reference in sdk/src/math.ts, and is replayed here through the Move code
/// (the math helpers, real pools in a test_scenario, and a real TransferPolicy).
module flash_kiosk::vectors_tests;

use flash_kiosk::collectible::Collectible;
use flash_kiosk::math;
use flash_kiosk::pool::{Pool, LpCoin};
use flash_kiosk::royalty_rule;
use flash_kiosk::test_utils::{Self as tu, ALPHA, BETA};
use std::unit_test::{assert_eq, destroy};
use sui::coin::Coin;
use sui::test_scenario::Scenario;
use sui::transfer_policy;

/// LP markers: the i-th pool created inside a test is `Pool<ALPHA, BETA, Mi>`.
public struct M0 {}
public struct M1 {}
public struct M2 {}
public struct M3 {}
public struct M4 {}
public struct M5 {}
public struct M6 {}
public struct M7 {}
public struct M8 {}
public struct M9 {}
public struct M10 {}
public struct M11 {}
public struct M12 {}
public struct M13 {}
public struct M14 {}
public struct M15 {}
public struct M16 {}
public struct M17 {}
public struct M18 {}
public struct M19 {}
public struct M20 {}
public struct M21 {}
public struct M22 {}
public struct M23 {}

/// Creates a fresh pool whose LP marker is `M` (a marker backs exactly one
/// pool, so every vector of a test uses its own) and returns it with the
/// creator's LP coin.
fun new_pool<M>(
    scenario: &mut Scenario,
    reserve_a: u64,
    reserve_b: u64,
): (Pool<ALPHA, BETA, M>, Coin<LpCoin<M>>) {
    scenario.next_tx(tu::alice());
    let (lp, cap) = tu::new_pool<M>(scenario, reserve_a, reserve_b);
    destroy(cap);
    scenario.next_tx(tu::alice());
    (tu::take_pool<M>(scenario), lp)
}

fun check_mul_div(a: u64, b: u64, d: u64, down: u64, up: u64) {
    assert_eq!(math::mul_div_down!(a, b, d), down);
    assert_eq!(math::mul_div_up!(a, b, d), up);
}

fun check_amount_out(
    amount_in: u64,
    reserve_in: u64,
    reserve_out: u64,
    fee_bps: u64,
    out: u64,
    fee: u64,
) {
    let (actual_out, actual_fee) = math::amount_out(amount_in, reserve_in, reserve_out, fee_bps);
    assert_eq!(actual_out, out);
    assert_eq!(actual_fee, fee);
}

fun check_flash_fee(amount: u64, fee_bps: u64, fee: u64) {
    assert_eq!(math::fee_up!(amount, fee_bps), fee);
}

fun check_pool_swap<M>(
    scenario: &mut Scenario,
    reserve_a: u64,
    reserve_b: u64,
    amount_in: u64,
    out: u64,
) {
    let (mut p, lp) = new_pool<M>(scenario, reserve_a, reserve_b);
    let coin_in = tu::mint<ALPHA>(scenario, amount_in);
    let coin_out = p.swap_a_for_b(coin_in, out, scenario.ctx());
    assert_eq!(tu::burn(coin_out), out);
    destroy(lp);
    tu::return_pool(p);
}

fun check_deposit<M>(
    scenario: &mut Scenario,
    reserve_a: u64,
    reserve_b: u64,
    amount_a: u64,
    amount_b: u64,
    lp_minted: u64,
    used_a: u64,
    used_b: u64,
) {
    let (mut p, lp0) = new_pool<M>(scenario, reserve_a, reserve_b);
    let a = tu::mint<ALPHA>(scenario, amount_a);
    let b = tu::mint<BETA>(scenario, amount_b);
    let (lp, refund_a, refund_b) = p.add_liquidity(a, b, lp_minted, scenario.ctx());
    assert_eq!(tu::burn(lp), lp_minted);
    assert_eq!(tu::burn(refund_a), amount_a - used_a);
    assert_eq!(tu::burn(refund_b), amount_b - used_b);
    destroy(lp0);
    tu::return_pool(p);
}

fun check_withdraw<M>(
    scenario: &mut Scenario,
    reserve_a: u64,
    reserve_b: u64,
    lp: u64,
    amount_a: u64,
    amount_b: u64,
) {
    let (mut p, mut lp0) = new_pool<M>(scenario, reserve_a, reserve_b);
    let burn = lp0.split(lp, scenario.ctx());
    let (a, b) = p.remove_liquidity(burn, amount_a, amount_b, scenario.ctx());
    assert_eq!(tu::burn(a), amount_a);
    assert_eq!(tu::burn(b), amount_b);
    destroy(lp0);
    tu::return_pool(p);
}

fun check_royalty(ctx: &mut TxContext, price: u64, bps: u64, min_amount: u64, fee: u64) {
    let (mut policy, cap) = transfer_policy::new_for_testing<Collectible>(ctx);
    royalty_rule::add(&mut policy, &cap, bps, min_amount);
    assert_eq!(royalty_rule::fee_amount(&policy, price), fee);
    destroy(policy.destroy_and_withdraw(cap, ctx));
}

#[test]
fun mul_div_vectors() {
    check_mul_div(
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
        18446744073709551615,
    );
    check_mul_div(18446744073709551615, 1, 2, 9223372036854775807, 9223372036854775808);
    check_mul_div(1, 1, 3, 0, 1);
    check_mul_div(0, 5, 7, 0, 0);
    check_mul_div(35198417133818, 21, 930359, 794496274, 794496275);
    check_mul_div(6, 33588446220769, 399297043188950751, 0, 1);
    check_mul_div(103449456161600078, 0, 29425056460744361, 0, 0);
    check_mul_div(864, 32907, 560618124042, 0, 1);
    check_mul_div(2907, 7, 47, 432, 433);
    check_mul_div(56516093653545042, 31, 4291, 408296178806780, 408296178806781);
    check_mul_div(234731950927826, 910945449, 217159805687237, 984657366, 984657367);
    check_mul_div(149865996042, 36, 1359, 3969960160, 3969960161);
    check_mul_div(460653072404003, 13270540, 4209463201267546, 1452231, 1452232);
    check_mul_div(880961874141986279, 606694830171, 10172382874695995402, 52541771304, 52541771305);
    check_mul_div(1982716883, 3360235, 127592321, 52216266, 52216267);
    check_mul_div(433800354, 5, 63910819726, 0, 1);
    check_mul_div(3066923811825785, 215399, 5269226891103, 125371773, 125371774);
    check_mul_div(1995, 1715543302068, 3252762059625, 1052, 1053);
    check_mul_div(486175520051362954, 1, 17, 28598560003021350, 28598560003021351);
    check_mul_div(3861, 280685780, 845938450144917, 0, 1);
    check_mul_div(6930538937320, 7, 3877, 12513224803, 12513224804);
    check_mul_div(1043, 220095308, 2663894243, 86, 87);
    check_mul_div(457922, 56, 3901, 6573, 6574);
    check_mul_div(4180231299355805, 9514350, 548010783436082297, 72575, 72576);
}

#[test]
fun amount_out_vectors() {
    check_amount_out(178821791, 39, 288, 28, 287, 500702);
    check_amount_out(8190646124, 37337789061, 1703571844, 62, 304915543, 50782006);
    check_amount_out(
        313878013874922,
        122366050381977858,
        2958693064577815,
        37,
        7541913330600,
        1161348651338,
    );
    check_amount_out(1705426209, 4293, 208504843255, 43, 208504316128, 7333333);
    check_amount_out(121, 18878, 33412265601555, 33, 211047050857, 1);
    check_amount_out(788870765510, 10, 81458764, 79, 81458763, 6232079048);
    check_amount_out(1859814974022, 8114310099, 34, 58, 33, 10786926850);
    check_amount_out(136868409600082, 89781, 428, 50, 427, 684342048001);
    check_amount_out(362340006, 8319706388, 28461641, 45, 1182706, 1630531);
    check_amount_out(
        54811979659534132,
        62154316849116408,
        911476030,
        66,
        425627269,
        361759065752926,
    );
    check_amount_out(117090, 2250279, 1597, 60, 78, 703);
    check_amount_out(931838, 7867, 80, 35, 79, 3262);
    check_amount_out(204256476336524411, 2951568420728094, 175, 3, 172, 61276942900958);
    check_amount_out(75, 1341397081, 1676584882597, 47, 92491, 1);
    check_amount_out(4939218462531316134, 220, 4, 67, 3, 33092763698959819);
    check_amount_out(964, 277246080751672821, 18053, 49, 0, 5);
    check_amount_out(
        2585739401027353240,
        111284818565,
        3101225945,
        11,
        3101225811,
        2844313341130089,
    );
    check_amount_out(3773317307105027768, 177, 7024892687890, 51, 7024892687889, 19243918266235642);
    check_amount_out(927888231, 48415437, 610, 97, 579, 9000516);
    check_amount_out(485, 26001663300, 742, 64, 0, 4);
    check_amount_out(
        836657792041483,
        1059628451594002,
        63002814788245,
        31,
        27749165424990,
        2593639155329,
    );
    check_amount_out(17191, 1848376937941, 52122, 45, 0, 78);
    check_amount_out(5080743789581, 32785858801, 475346707206155, 13, 472295036974836, 6604966927);
    check_amount_out(36593576073, 5, 97356761506999994, 66, 97356761493609175, 241517603);
}

#[test]
fun flash_fee_vectors() {
    check_flash_fee(7164, 65, 47);
    check_flash_fee(6691378, 6, 4015);
    check_flash_fee(897718570801511, 61, 5476083281890);
    check_flash_fee(2, 12, 1);
    check_flash_fee(89992922428, 50, 449964613);
    check_flash_fee(114953211, 18, 206916);
    check_flash_fee(264675453479708, 86, 2276208899926);
    check_flash_fee(339928445, 11, 373922);
    check_flash_fee(880, 86, 8);
    check_flash_fee(1001829059060206420, 34, 3406218800804702);
    check_flash_fee(433562451342897, 85, 3685280836415);
    check_flash_fee(618194225243419, 93, 5749206294764);
    check_flash_fee(849426660, 59, 5011618);
    check_flash_fee(5289524, 8, 4232);
    check_flash_fee(424003363828, 57, 2416819174);
    check_flash_fee(1528, 25, 4);
    check_flash_fee(7214278565, 68, 49057095);
    check_flash_fee(1871311711178440, 23, 4304016935711);
    check_flash_fee(30606777, 8, 24486);
    check_flash_fee(417262559802, 82, 3421552991);
    check_flash_fee(1, 27, 1);
    check_flash_fee(86, 8, 1);
    check_flash_fee(21725950211524, 41, 89076395868);
    check_flash_fee(46746, 41, 192);
}

#[test]
fun pool_swap_vectors() {
    let mut scenario = tu::begin();
    check_pool_swap<M0>(&mut scenario, 1098350, 1071823, 685, 665);
    check_pool_swap<M1>(&mut scenario, 1076192, 1014324, 31, 28);
    check_pool_swap<M2>(&mut scenario, 1067622, 46756860786329, 1658408, 28411523565376);
    check_pool_swap<M3>(&mut scenario, 1000001, 22929912596, 240468, 4434255396);
    check_pool_swap<M4>(&mut scenario, 1001467, 1000001, 3030969, 751086);
    check_pool_swap<M5>(&mut scenario, 8669442627164, 24346496420646, 2729521700238, 5816542158021);
    check_pool_swap<M6>(&mut scenario, 1050788, 28422501, 7, 162);
    check_pool_swap<M7>(&mut scenario, 7635350194409, 234518566, 22188740602, 677516);
    check_pool_swap<M8>(&mut scenario, 1000048, 1001587, 16822, 16519);
    check_pool_swap<M9>(&mut scenario, 2451590, 1003645, 131, 53);
    check_pool_swap<M10>(&mut scenario, 1000002, 1001200, 9, 8);
    check_pool_swap<M11>(&mut scenario, 1927571288, 1270400, 862449, 566);
    check_pool_swap<M12>(&mut scenario, 1000252, 1000055, 79, 77);
    check_pool_swap<M13>(&mut scenario, 2017946, 242610569, 8, 841);
    check_pool_swap<M14>(&mut scenario, 1677125985, 3538145071, 109704267, 216616241);
    check_pool_swap<M15>(&mut scenario, 1226883169, 795048052, 3, 1);
    check_pool_swap<M16>(&mut scenario, 17127998068363, 1000023, 14780317516, 859);
    check_pool_swap<M17>(&mut scenario, 1002632, 4426424161256, 2618, 11492722211);
    check_pool_swap<M18>(&mut scenario, 1000035, 57310798, 2790, 158933);
    check_pool_swap<M19>(&mut scenario, 1000061, 1000002, 54132, 51202);
    check_pool_swap<M20>(&mut scenario, 1007897, 64056016, 182161, 9780043);
    check_pool_swap<M21>(&mut scenario, 1000163, 2633963, 113950, 268672);
    check_pool_swap<M22>(&mut scenario, 6681931477, 790164292, 21537, 2539);
    check_pool_swap<M23>(&mut scenario, 1469307, 2563224378, 167, 289556);
    scenario.end();
}

#[test]
fun deposit_vectors() {
    let mut scenario = tu::begin();
    check_deposit<M0>(&mut scenario, 1000834, 15320334, 28164, 2994, 765, 196, 2994);
    check_deposit<M1>(&mut scenario, 1015824, 11904144, 66786, 102, 29, 9, 100);
    check_deposit<M2>(&mut scenario, 1000044, 1001490, 334, 424784, 334, 334, 335);
    check_deposit<M3>(&mut scenario, 1013297, 688465165, 589, 13433, 515, 20, 13424);
    check_deposit<M4>(&mut scenario, 1000001, 3284966563427, 33, 1685539, 929, 1, 1683764);
    check_deposit<M5>(&mut scenario, 1000080, 1216950, 33, 2074483, 36, 33, 40);
    check_deposit<M6>(&mut scenario, 481475990517, 1887186091706, 4, 1139, 7, 4, 14);
    check_deposit<M7>(
        &mut scenario,
        1000001,
        77362506593318,
        254,
        4342823576,
        493750,
        57,
        4342823287,
    );
    check_deposit<M8>(
        &mut scenario,
        1117812,
        4623034325297,
        897,
        6428304240755,
        1824196,
        897,
        3709801517,
    );
    check_deposit<M9>(&mut scenario, 1000002, 1240108, 149, 242856, 165, 149, 184);
    check_deposit<M10>(&mut scenario, 1000000, 1000538, 52, 5856, 52, 52, 53);
    check_deposit<M11>(&mut scenario, 198685530, 2153206, 60268, 23326, 6274, 60268, 654);
    check_deposit<M12>(&mut scenario, 1000048, 10786856442431, 8, 406550234, 26274, 8, 86290548);
    check_deposit<M13>(&mut scenario, 6652568, 24189293, 13, 104, 24, 13, 46);
    check_deposit<M14>(&mut scenario, 1000679, 31268868, 30674, 14831345, 171466, 30674, 958489);
    check_deposit<M15>(&mut scenario, 1945473, 56632664, 36952, 517855, 95981, 17790, 517853);
    check_deposit<M16>(&mut scenario, 1003182, 1083968, 924742, 108832, 104697, 100721, 108832);
    check_deposit<M17>(
        &mut scenario,
        240277798,
        836575669927065,
        31,
        2958294238,
        57843,
        31,
        107931100,
    );
    check_deposit<M18>(&mut scenario, 53143486294234, 1878167, 39178, 16, 7, 37236, 1);
    check_deposit<M19>(&mut scenario, 1173195, 1000000, 319423, 1427, 1545, 1674, 1427);
    check_deposit<M20>(
        &mut scenario,
        15344943006,
        148509430,
        826360523,
        106885515,
        81295019,
        826360523,
        7997575,
    );
    check_deposit<M21>(&mut scenario, 3390242672820, 1334804, 8206507, 57292, 5149, 8205963, 4);
    check_deposit<M22>(
        &mut scenario,
        17871873892825,
        1453471,
        8831141207578,
        15005,
        52616003,
        184501420330,
        15005,
    );
    check_deposit<M23>(&mut scenario, 1004336, 1371581, 6, 3, 2, 2, 3);
    scenario.end();
}

#[test]
fun withdraw_vectors() {
    let mut scenario = tu::begin();
    check_withdraw<M0>(&mut scenario, 1003933, 25978252465718, 869223297, 170875, 4421645895052);
    check_withdraw<M1>(&mut scenario, 1047337725, 7714115796, 366, 134, 993);
    check_withdraw<M2>(
        &mut scenario,
        20551323035302,
        4945743722,
        101224037717,
        6525108619937,
        1570288926,
    );
    check_withdraw<M3>(&mut scenario, 4520859662, 7735863, 7064, 170768, 292);
    check_withdraw<M4>(&mut scenario, 25516404707, 34604512344170, 29396, 798, 1082542);
    check_withdraw<M5>(&mut scenario, 1074327, 1000152, 124, 128, 119);
    check_withdraw<M6>(&mut scenario, 10910095187, 2206248820, 12, 26, 5);
    check_withdraw<M7>(&mut scenario, 19848054328, 50648669292, 39523, 24741, 63135);
    check_withdraw<M8>(&mut scenario, 2371837, 1639717872, 7964, 302, 209398);
    check_withdraw<M9>(&mut scenario, 150760686535, 75556096493, 7, 9, 4);
    check_withdraw<M10>(&mut scenario, 1012204, 1041692, 17, 16, 17);
    check_withdraw<M11>(&mut scenario, 495298691, 1003963, 19243, 427412, 866);
    check_withdraw<M12>(&mut scenario, 3219854, 1000110, 6, 10, 3);
    check_withdraw<M13>(&mut scenario, 41325648980123, 161945313587, 22659, 361964, 1418);
    check_withdraw<M14>(&mut scenario, 1025661582764, 169823122195, 12399750, 30473094, 5045559);
    check_withdraw<M15>(&mut scenario, 65243683, 1513976451, 193563, 40182, 932422);
    check_withdraw<M16>(&mut scenario, 1000924, 1000011, 12, 12, 11);
    check_withdraw<M17>(&mut scenario, 1000502, 1000473, 1379, 1379, 1378);
    check_withdraw<M18>(&mut scenario, 472650240466605, 1005530, 1432951676, 31067332836455, 66093);
    check_withdraw<M19>(
        &mut scenario,
        2222790242,
        370476470044484,
        78279124306,
        191740954,
        31957811652078,
    );
    check_withdraw<M20>(&mut scenario, 158535332779, 1002585, 15299, 6083667, 38);
    check_withdraw<M21>(&mut scenario, 201556827175306, 8324271586357, 15087693, 74241796, 3066176);
    check_withdraw<M22>(&mut scenario, 1808603954, 2141817084, 12, 11, 13);
    check_withdraw<M23>(&mut scenario, 19693598842188, 341744508053975, 150, 36, 624);
    scenario.end();
}

#[test]
fun royalty_vectors() {
    let mut ctx = tx_context::dummy();
    check_royalty(&mut ctx, 2088615644, 7463, 316, 1558733856);
    check_royalty(&mut ctx, 1, 3965, 15131463, 15131463);
    check_royalty(&mut ctx, 45507903, 3606, 631537, 16410150);
    check_royalty(&mut ctx, 7217839, 5059, 3077393, 3651505);
    check_royalty(&mut ctx, 258119477730, 1411, 15115, 36420658308);
    check_royalty(&mut ctx, 12252832, 4685, 11, 5740452);
    check_royalty(&mut ctx, 35, 9096, 1764063, 1764063);
    check_royalty(&mut ctx, 15835, 7756, 19529, 19529);
    check_royalty(&mut ctx, 192890, 5737, 393557283, 393557283);
    check_royalty(&mut ctx, 13350, 7291, 26, 9734);
    check_royalty(&mut ctx, 5278, 6867, 3296135, 3296135);
    check_royalty(&mut ctx, 461605130893, 2105, 7351547, 97167880053);
    check_royalty(&mut ctx, 6086, 8335, 867, 5073);
    check_royalty(&mut ctx, 8809439, 3155, 789, 2779379);
    check_royalty(&mut ctx, 442888, 4483, 9285, 198547);
    check_royalty(&mut ctx, 805511691656, 5992, 990161849, 482662605641);
    check_royalty(&mut ctx, 33995579895, 8532, 3, 29005028767);
    check_royalty(&mut ctx, 3995151, 7540, 9, 3012344);
    check_royalty(&mut ctx, 376843, 9262, 4, 349032);
    check_royalty(&mut ctx, 719, 3705, 438, 438);
    check_royalty(&mut ctx, 42901177773, 1287, 302, 5521381580);
    check_royalty(&mut ctx, 3, 9473, 3438, 3438);
    check_royalty(&mut ctx, 188002, 7938, 3741, 149236);
    check_royalty(&mut ctx, 5, 7082, 42036911, 42036911);
}
