// SPDX-License-Identifier: MIT
/**
 * Generates `src/chain/abis.ts` from the Foundry artifacts in `contracts/out`.
 *
 * The ABIs are emitted as `as const` literals so viem can infer argument and return types. The generated file is
 * committed (TypeScript type-checks without a Solidity build); `--check` fails if it is stale, which CI runs right
 * after `forge build`.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'contracts', 'out');
const target = join(root, 'src', 'chain', 'abis.ts');

const contracts: readonly [file: string, contract: string, exportName: string][] = [
  ['TestUSD.sol', 'TestUSD', 'testUsdAbi'],
  ['SettlementLog.sol', 'SettlementLog', 'settlementLogAbi'],
  ['BudgetExecutor.sol', 'BudgetExecutor', 'budgetExecutorAbi'],
  ['PaymentEscrow.sol', 'PaymentEscrow', 'paymentEscrowAbi'],
  ['AgentAccount.sol', 'AgentAccount', 'agentAccountAbi'],
  ['AgentAccountFactory.sol', 'AgentAccountFactory', 'agentAccountFactoryAbi'],
  ['IdentityRegistry.sol', 'IdentityRegistry', 'identityRegistryAbi'],
  ['ReputationRegistry.sol', 'ReputationRegistry', 'reputationRegistryAbi'],
  ['ValidationRegistry.sol', 'ValidationRegistry', 'validationRegistryAbi'],
];

function render(): string {
  const parts = [
    '// SPDX-License-Identifier: MIT',
    '// AUTO-GENERATED by scripts/gen-abis.ts from contracts/out. Do not edit by hand; run `npm run abis`.',
    '',
  ];
  for (const [file, contract, exportName] of contracts) {
    const artifactPath = join(outDir, file, `${contract}.json`);
    if (!existsSync(artifactPath)) {
      throw new Error(`missing artifact ${artifactPath}; run \`forge build\` in contracts/ first`);
    }
    const artifact = JSON.parse(readFileSync(artifactPath, 'utf8')) as { abi: unknown };
    parts.push(`export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;`, '');
  }
  return parts.join('\n');
}

const generated = render();
if (process.argv.includes('--check')) {
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (current.replace(/\r\n/g, '\n') !== generated) {
    console.error('src/chain/abis.ts is out of date: run `npm run abis` after `forge build`.');
    process.exit(1);
  }
  console.log('src/chain/abis.ts is up to date.');
} else {
  writeFileSync(target, generated);
  console.log(`wrote ${target}`);
}
