// SPDX-License-Identifier: MIT
pragma solidity 0.8.37;

import {Test} from "forge-std/Test.sol";
import {ZkGate} from "../../src/ZkGate.sol";
import {PUBLIC_SIGNALS} from "../../src/interfaces/IVerifiers.sol";

/// @title FixtureLoader
/// @notice Loads the committed snarkjs proof fixtures (generated by `npm run fixtures`, verified by
///         `npm run fixtures -- --check`) and deploys gates at the fixed addresses those proofs are
///         scoped to.
/// @dev The proofs bind appScope = keccak256(chainId, gate address, actionId, epoch) and
///      recipient = 0xB0B, so every test pins the chain id, warps to the fixture timestamp and
///      deploys the gate with `deployCodeTo` at `gate.json`'s address.
abstract contract FixtureLoader is Test {
    /// @notice A Groth16 proof plus its public signals.
    struct Groth16Fixture {
        uint256[2] a;
        uint256[2][2] b;
        uint256[2] c;
        uint256[PUBLIC_SIGNALS] pub;
    }

    /// @notice A PLONK proof plus its public signals.
    struct PlonkFixture {
        uint256[24] proof;
        uint256[PUBLIC_SIGNALS] pub;
    }

    /// @notice Deployment constants the fixtures were proven for (gate.json).
    struct GateFixture {
        uint256 chainId;
        address gateAddress;
        address gateBAddress;
        bytes32 actionId;
        uint256 epochDuration;
        uint256 timestamp;
        uint256 epoch;
        uint256 appScope;
        uint256 appScopeB;
        address recipient;
        uint256 currentDate;
        uint256 issuerRoot;
        uint256 revocationRoot;
        uint256[16] sanctioned;
    }

    string internal constant DIR = "test/fixtures/";

    /// @dev Grace periods used by the default test deployment.
    uint256 internal constant ISSUER_GRACE = 1 days;
    uint256 internal constant REVOCATION_GRACE = 1 hours;

    function _read(string memory file) internal view returns (string memory) {
        return vm.readFile(string.concat(DIR, file));
    }

    function _groth16At(string memory json, string memory prefix) internal pure returns (Groth16Fixture memory f) {
        uint256[] memory a = vm.parseJsonUintArray(json, string.concat(prefix, ".a"));
        uint256[] memory b0 = vm.parseJsonUintArray(json, string.concat(prefix, ".b[0]"));
        uint256[] memory b1 = vm.parseJsonUintArray(json, string.concat(prefix, ".b[1]"));
        uint256[] memory c = vm.parseJsonUintArray(json, string.concat(prefix, ".c"));
        uint256[] memory p = vm.parseJsonUintArray(json, string.concat(prefix, ".pub"));
        require(p.length == PUBLIC_SIGNALS, "bad pub length");
        f.a = [a[0], a[1]];
        f.b = [[b0[0], b0[1]], [b1[0], b1[1]]];
        f.c = [c[0], c[1]];
        for (uint256 i = 0; i < PUBLIC_SIGNALS; i++) {
            f.pub[i] = p[i];
        }
    }

    /// @notice Load a top-level Groth16 fixture file (keys a/b/c/pub).
    function loadGroth16(string memory file) internal view returns (Groth16Fixture memory) {
        return _groth16At(_read(file), "");
    }

    /// @notice Load a nested Groth16 fixture (e.g. prefix ".proofA").
    function loadGroth16Nested(string memory file, string memory prefix) internal view returns (Groth16Fixture memory) {
        return _groth16At(_read(file), prefix);
    }

    /// @notice Load the PLONK fixture (keys proof/pub).
    function loadPlonk(string memory file) internal view returns (PlonkFixture memory f) {
        string memory json = _read(file);
        uint256[] memory pr = vm.parseJsonUintArray(json, ".proof");
        uint256[] memory p = vm.parseJsonUintArray(json, ".pub");
        require(pr.length == 24, "bad proof length");
        require(p.length == PUBLIC_SIGNALS, "bad pub length");
        for (uint256 i = 0; i < 24; i++) {
            f.proof[i] = pr[i];
        }
        for (uint256 i = 0; i < PUBLIC_SIGNALS; i++) {
            f.pub[i] = p[i];
        }
    }

    /// @notice Load the deployment constants of the fixtures.
    function loadGate() internal view returns (GateFixture memory g) {
        string memory json = _read("gate.json");
        g.chainId = vm.parseJsonUint(json, ".chainId");
        g.gateAddress = vm.parseJsonAddress(json, ".gateAddress");
        g.gateBAddress = vm.parseJsonAddress(json, ".gateBAddress");
        g.actionId = vm.parseJsonBytes32(json, ".actionId");
        g.epochDuration = vm.parseJsonUint(json, ".epochDuration");
        g.timestamp = vm.parseJsonUint(json, ".timestamp");
        g.epoch = vm.parseJsonUint(json, ".epoch");
        g.appScope = vm.parseJsonUint(json, ".appScope");
        g.appScopeB = vm.parseJsonUint(json, ".appScopeB");
        g.recipient = vm.parseJsonAddress(json, ".recipient");
        g.currentDate = vm.parseJsonUint(json, ".currentDate");
        g.issuerRoot = vm.parseJsonUint(json, ".issuerRoot");
        g.revocationRoot = vm.parseJsonUint(json, ".revocationRoot");
        uint256[] memory s = vm.parseJsonUintArray(json, ".sanctioned");
        require(s.length == 16, "bad sanctioned length");
        for (uint256 i = 0; i < 16; i++) {
            g.sanctioned[i] = s[i];
        }
    }

    /// @notice Pin the chain id and block time the fixtures were proven for.
    function useFixtureChain(GateFixture memory g) internal {
        vm.chainId(g.chainId);
        vm.warp(g.timestamp);
    }

    /// @notice The default configuration matching the fixtures' public inputs.
    function fixtureConfig(GateFixture memory g, address groth16Verifier, address plonkVerifier, address admin)
        internal
        pure
        returns (ZkGate.GateConfig memory cfg)
    {
        cfg = ZkGate.GateConfig({
            groth16Verifier: groth16Verifier,
            plonkVerifier: plonkVerifier,
            admin: admin,
            actionId: g.actionId,
            epochDuration: g.epochDuration,
            issuerRootGracePeriod: ISSUER_GRACE,
            revocationRootGracePeriod: REVOCATION_GRACE,
            issuerRoot: g.issuerRoot,
            revocationRoot: g.revocationRoot,
            currentDate: g.currentDate,
            sanctioned: g.sanctioned
        });
    }

    /// @notice Deploy ZkGate at a fixed address (its scope depends on the address).
    function deployGateAt(address where, ZkGate.GateConfig memory cfg) internal returns (ZkGate) {
        deployCodeTo("ZkGate.sol:ZkGate", abi.encode(cfg), where);
        return ZkGate(where);
    }
}
